# Generated by Django 4.0.3 on 2022-04-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Django', 'Django'), ('Node', 'Node'), ('React Native', 'React Native'), ('Fullstack Node', 'Fullstack Node'), ('Flutter', 'Flutter'), ('Fullstack Django', 'Fullstack Django')], max_length=20)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.interviewer')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_question', models.TextField(max_length=255)),
                ('resources', models.SlugField(blank=True, max_length=100)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stack')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=500)),
                ('rating', models.IntegerField(blank=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stack')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('meet_link', models.SlugField(blank=True, max_length=255)),
                ('time', models.TimeField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.questionnaire')),
            ],
        ),
    ]
