# Generated by Django 4.0.3 on 2022-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstack',
            name='name',
            field=models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Django', 'Django'), ('Node', 'Node'), ('ReactNative', 'ReactNative'), ('FullstackNode', 'FullstackNode'), ('Flutter', 'Flutter'), ('FullstackDjango', 'FullstackDjango')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stack',
            name='name',
            field=models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Django', 'Django'), ('Node', 'Node'), ('ReactNative', 'ReactNative'), ('FullstackNode', 'FullstackNode'), ('Flutter', 'Flutter'), ('FullstackDjango', 'FullstackDjango')], max_length=20),
        ),
    ]
