# Generated by Django 4.0.3 on 2022-04-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='applicationstack',
            name='interviewee',
        ),
        migrations.AddField(
            model_name='applicationstack',
            name='application',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.application'),
        ),
    ]
