# Generated by Django 4.0.3 on 2022-05-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interviewee',
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewee',
            field=models.ManyToManyField(to='accounts.interviewee'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.panel'),
        ),
    ]
