# Generated by Django 4.0.3 on 2022-04-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stack_task_questionnaire_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewee',
            name='resume_link',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stack',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.interviewee')),
                ('stack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.stack')),
            ],
        ),
    ]
