# Generated by Django 3.2.8 on 2022-04-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stack_task_questionnaire_interview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
    ]
