# Generated by Django 4.0.3 on 2022-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_resources_task_task_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_resources',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
