# Generated by Django 4.0.3 on 2022-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220618_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstack',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
