# Generated by Django 4.0.3 on 2022-05-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_application_stack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstack',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack', to='accounts.application'),
        ),
    ]
