# Generated by Django 4.0.3 on 2022-05-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_interview_interviewee_interview_interviewee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='stack',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.applicationstack'),
        ),
    ]
