# Generated by Django 4.0.3 on 2022-05-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_questionnaire_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interviewee',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='panel',
        ),
        migrations.AddField(
            model_name='panel',
            name='interviewees',
            field=models.ManyToManyField(to='accounts.interviewee'),
        ),
        migrations.AddField(
            model_name='panel',
            name='interviewers',
            field=models.ManyToManyField(to='accounts.interviewer'),
        ),
    ]
