# Generated by Django 4.0.3 on 2022-05-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_interview_interviewee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='resources',
            field=models.FileField(blank=True, max_length=200, upload_to='media/resources'),
        ),
    ]
