# Generated by Django 4.0.3 on 2022-05-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_stack_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_resources',
            field=models.FileField(blank=True, upload_to='media/tasks'),
        ),
    ]
